<?php  echo $this->prueba;?>
<p> </p>  
<form id="form1" action="<?php echo BASE_URL?>post/nuevo" method="post">
  
    <input type="hidden" name="guardar"  value="1">
    <p>Titulo :<br/>
        <input type="text" name="titulo" value="<?php if(isset($this->datos['titulo'])) echo $this->datos['titulo'];?>"  /></p>
    <p>Mensaje :<br/>
        <textarea name="cuerpo"  cols="45" rows="4" ><?php if(isset($this->datos['cuerpo'])) echo $this->datos['cuerpo'];?></textarea>
    </p>
    <p><input type="submit" class="button" value="Guardar"/></p>
</form>